name: Az login
description: Do az login
inputs:
  subscription:
    description: Subscription number
    required: true
  tenant-id:
    description: Tenant id
  client-id: 
    description: Client id
  client-secret: 
    description: Client secret

runs:
  using: 'composite'
  steps:
    - name: Login
      shell: bash
      run: |
        set -e
        az login --service-principal -u ${{ inputs.client-id }} -p ${{ inputs.client-secret }} --tenant ${{ inputs.tenant-id }} > /dev/null
        az account set --subscription ${{ inputs.subscription }}

